### ISSUE TITLE
いいところ診断に優しさを追加したい

### ISSUE THREAD

**Issue by haru0604** [haru0604/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by haru0604** [comment]
これから対応します。

**Comment by tasuko0604** [comment]
1451bfb で対応されました。

**Comment by haru0604** [comment]
1451bfb で対応されました。
